// Do not edit. This file is machine generated by the Resource DLL Wizard.

library M2Server;

{ITE} {DFMFileType} {ActionSpeedConfig.dfm}
{ITE} {DFMFileType} {AttackSabukWallConfig.dfm}
{ITE} {DFMFileType} {CastleManage.dfm}
{ITE} {DFMFileType} {ConfigMerchant.dfm}
{ITE} {DFMFileType} {ConfigMonGen.dfm}
{ITE} {DFMFileType} {EditCompoundInfo.dfm}
{ITE} {DFMFileType} {EngineRegister.dfm}
{ITE} {DFMFileType} {FrmShop.dfm}
{ITE} {DFMFileType} {FSrvValue.dfm}
{ITE} {DFMFileType} {FunctionConfig.dfm}
{ITE} {DFMFileType} {GameCommand.dfm}
{ITE} {DFMFileType} {GameConfig.dfm}
{ITE} {DFMFileType} {GeneralConfig.dfm}
{ITE} {DFMFileType} {HumanInfo.dfm}
{ITE} {DFMFileType} {IdSrvClient.dfm}
{ITE} {DFMFileType} {ItemSet.dfm}
{ITE} {DFMFileType} {LocalDB.dfm}
{ITE} {DFMFileType} {MonsterConfig.dfm}
{ITE} {DFMFileType} {OnlineEmail.dfm}
{ITE} {DFMFileType} {OnlineMsg.dfm}
{ITE} {DFMFileType} {svMain.dfm}
{ITE} {DFMFileType} {ViewCompoundInfo.dfm}
{ITE} {DFMFileType} {ViewKernelInfo.dfm}
{ITE} {DFMFileType} {ViewLevel.dfm}
{ITE} {DFMFileType} {ViewList.dfm}
{ITE} {DFMFileType} {ViewOnlineHuman.dfm}
{ITE} {DFMFileType} {ViewSession.dfm}
{ITE} {RCFileType} {M2Server_DRC.rc}

{$R 'ActionSpeedConfig.dfm' frmActionSpeed:TForm}
{$R 'AttackSabukWallConfig.dfm' FrmAttackSabukWall:TForm}
{$R 'CastleManage.dfm' frmCastleManage:TForm}
{$R 'ConfigMerchant.dfm' frmConfigMerchant:TForm}
{$R 'ConfigMonGen.dfm' frmConfigMonGen:TForm}
{$R 'EditCompoundInfo.dfm' EditCompoundInfoForm:TForm}
{$R 'EngineRegister.dfm' FrmRegister:TForm}
{$R 'FrmShop.dfm' FormShop:TForm}
{$R 'FSrvValue.dfm' FrmServerValue:TForm}
{$R 'FunctionConfig.dfm' frmFunctionConfig:TForm}
{$R 'GameCommand.dfm' frmGameCmd:TForm}
{$R 'GameConfig.dfm' frmGameConfig:TForm}
{$R 'GeneralConfig.dfm' frmGeneralConfig:TForm}
{$R 'HumanInfo.dfm' frmHumanInfo:TForm}
{$R 'IdSrvClient.dfm' FrmIDSoc:TForm}
{$R 'ItemSet.dfm' frmItemSet:TForm}
{$R 'LocalDB.dfm' FrmDB:TForm}
{$R 'MonsterConfig.dfm' frmMonsterConfig:TForm}
{$R 'OnlineEmail.dfm' frmOnlineEmail:TForm}
{$R 'OnlineMsg.dfm' frmOnlineMsg:TForm}
{$R 'svMain.dfm' FrmMain:TForm}
{$R 'ViewCompoundInfo.dfm' FrmViewCompoundInfo:TForm}
{$R 'ViewKernelInfo.dfm' frmViewKernelInfo:TForm}
{$R 'ViewLevel.dfm' frmViewLevel:TForm}
{$R 'ViewList.dfm' frmViewList:TForm}
{$R 'ViewOnlineHuman.dfm' frmViewOnlineHuman:TForm}
{$R 'ViewSession.dfm' frmViewSession:TForm}
{$R 'M2Server_DRC.res' 'M2Server_DRC.rc'}

{$E CHS}

begin
end.